apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-chat-redis
spec:
  selector:
    matchLabels:
      app: redis-chat-redis
      deployment: redis-chat
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-chat-redis
        deployment: redis-chat
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-chat-redis
    deployment: redis-chat
  name: redis-chat-redis-service
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis-chat-redis
