apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: redis-chat-web
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: riff-build
        source:
          git:
            url: https://github.com/doddatpivotal/redis-chat-app.git
            revision: master
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: gcr.io/fe-dpfeffer/redis-chat-web # Update with your registry location
      revisionTemplate:
        spec:
          container:
            image: gcr.io/fe-dpfeffer/redis-chat-web # Update with your registry location
            env:
            - name: REDIS_HOST_NAME
              value: redis-chat-redis-service
            - name: FEEDER_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-chat-web-config
                  key: FEEDER_URL
# Setup a configmap similar   to `kubectl create configmap redis-chat-web-config --from-literal=FEEDER_URL="http://channel-feeder.default.<CUSTOM_DOMAIN>"`