apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: redis-chat-web
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dpfefferatpivotal/redis-chat:potty
            env:
            - name: REDIS_HOST_NAME
              value: redis-chat-redis-service
            - name: FEEDER_URL
              value: "http://channel-feeder.default.doddpfeffer.com" # replace doddpfeffer.com with your custom domain
            - name: version
              value: "6"
